//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3_Bogdanova.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long ID_Order { get; set; }
        public long ID_Worker { get; set; }
        public long ID_Client { get; set; }
        public long ID_Catalog { get; set; }
        public long ID_Status { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual Client Client { get; set; }
        public virtual Order_Status Order_Status { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
